spring.application.name=QuatroBytes
spring.profiles.active=dev
server.port=8081
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
api.quatrobytes.security.token.secret = ${JWT_SECRET:my-secret-key}